[package]
authors = ["Frederick Zhang <frederick888@tsundere.moe>"]
name = "mediaserver"
version = "0.1.0"

[dependencies]
clap = "2.25.1"
iron = "0.5.1"
lazy_static = "0.2.8"
slog = "2.0.6"
slog-term = "2.0.2"
url = "1.5.1"
